headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "C:\\workspace"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'No build step required'"

[build.environment]
NODE_VERSION = "18"
FIREBASE_API_KEY = "AIzaSyC5QpmTOMpI36qczNrQmicpMmnQC8PZCe8"
FIREBASE_AUTH_DOMAIN = "charlotte-a0d47.firebaseapp.com"
FIREBASE_PROJECT_ID = "charlotte-a0d47"
FIREBASE_STORAGE_BUCKET = "charlotte-a0d47.firebasestorage.app"
FIREBASE_MESSAGING_SENDER_ID = "971007838036"
FIREBASE_APP_ID = "1:971007838036:web:381b5c516ba841fef12ac1"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "*.js"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
X-Content-Type-Options = "nosniff"

[[headers]]
for = "*.css"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]