functionsDirectory = "C:\\workspace\\netlify\\functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\workspace"
publishOrigin = "config"
functions = "C:\\workspace\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
functions = "netlify/functions"

[functions]

[functions."*"]